import Head from 'next/head';

import { DUMMY_COSMETIC } from '@/dummy/cosmetic';
import { CosmeticListWithTitle, Flex, Header } from '@/components';
import styled from '@emotion/styled';

export default function CosmeticList() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main style={{ paddingInline: 34, paddingBlock: 80 }}>
        <FlexWithLine flexDirection="column" gap={32}>
          <CosmeticListWithTitle
            title={'SERUM'}
            cosmetics={[...Array(3)].map(() => DUMMY_COSMETIC)}
          />
          <CosmeticListWithTitle
            title={'SERUM'}
            cosmetics={[...Array(3)].map(() => DUMMY_COSMETIC)}
          />
          <CosmeticListWithTitle
            title={'SERUM'}
            cosmetics={[...Array(3)].map(() => DUMMY_COSMETIC)}
          />
        </FlexWithLine>
      </main>
    </>
  );
}

const FlexWithLine = styled(Flex)`
  & > div:not(:first-of-type) {
    padding-top: 16px;
    border-top: ${({ theme }) => `1px solid ${theme.colors.gray200}`};
  }
`;
