import Head from 'next/head';
import styled from '@emotion/styled';

import useLink from '@/hooks/useLink';
import { Header } from '@/components';
import { getRedirectFlag } from '@/utils';
import {
  LandingIntroSection,
  LandingWhatWeDoSection,
  LandingOurniksPlanetSection,
  LandingCharacterSection,
  LandingFindFriendSection,
} from '@/components/landing';
import Image from 'next/image';

export default function Home() {
  const link = useLink();

  if (getRedirectFlag()) {
    link.to('skinTypeTestResult');
  }

  return (
    <>
      <Head>
        <title>EGGY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <Background>
          <Image src="/background.png" alt="background" fill />
        </Background>
        <LandingIntroSection />
        <LandingWhatWeDoSection />
        <LandingOurniksPlanetSection />
        <LandingCharacterSection />
        <LandingFindFriendSection />
      </Main>
    </>
  );
}

const Main = styled.main`
  scroll-snap-type: y proximity;
  background-color: ${({ theme }) => theme.colors.black};
  position: relative;
`;

const Background = styled.div`
  position: absolute;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: 0;
`;
