import { Button, Icon, Text } from '@/components';
import { useTheme } from '@emotion/react';
import styled from '@emotion/styled';
import Head from 'next/head';

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ display: 'flex', paddingInline: 20, gap: 16 }}>
          <Button variant="outlined" Icon={<ColorLeftArrow color="primary" type="leftArrow" />}>
            Prev
          </Button>
          <Button variant="filled" Icon={<Icon type="rightArrow" />} iconPosition="end">
            Next
          </Button>
        </div>
        <div style={{ display: 'flex', paddingInline: 20, gap: 16, marginTop: 16 }}>
          <Button
            hierarchy="secondary"
            variant="outlined"
            Icon={<ColorLeftArrow color="secondary" type="leftArrow" />}
          >
            Prev
          </Button>
          <Button
            hierarchy="secondary"
            variant="filled"
            Icon={<Icon type="rightArrow" />}
            iconPosition="end"
          >
            Next
          </Button>
        </div>
        <Text variant="h1">Pretendard H1</Text>
        <Text variant="h2" fontWeight={800}>
          Pretendard H2
        </Text>
        <Text variant="h3" color={theme.colors.primary}>
          Pretendard H3
        </Text>
        <Text variant="h4" color={theme.colors.secondary}>
          Pretendard H4
        </Text>
        <Text variant="h5" color={theme.colors.teritiary}>
          Pretendard H5
        </Text>
        <Text variant="h6">Pretendard H6</Text>
        <Text variant="h7">Pretendard H7</Text>
        <Text variant="body1">Pretendard Body1</Text>
        <Text variant="body2">Pretendard Body2</Text>
        <Text variant="body3">Pretendard Body3</Text>
        <Text variant="body4">Pretendard Body4</Text>
        <Text variant="body5">Pretendard Body5</Text>
        <Text variant="h3" fontFamily="monteserrat">
          Monteserrat H3
        </Text>
        <Text variant="h3" fontFamily="playFair">
          PlayFair H3
        </Text>
        <Text variant="h3" fontFamily="bodoniModar">
          BodoniModar H3
        </Text>
      </main>
    </>
  );
}

const ColorLeftArrow = styled(Icon)<{ color: 'primary' | 'secondary' }>`
  & > path {
    fill: ${({ theme, color }) =>
      color === 'primary' ? theme.colors.primary : theme.colors.secondary};
  }
`;
