import { Header, SkeletonImage } from '@/components';
import useLink from '@/hooks/useLink';
import styled from '@emotion/styled';
import Head from 'next/head';
import React from 'react';

export default function LoginPage() {
  const link = useLink();
  const handleClickGoogleLogin = React.useCallback(() => {
    link.url(`${process.env.NEXT_PUBLIC_SERVER_API}/api/user/login/google`);
  }, [link]);
  return (
    <>
      <Head>
        <title>EGGY: Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content>
        <GoogleLoginButton onClick={handleClickGoogleLogin}>
          <SkeletonImage
            src="/GoogleLogin.png"
            objectFit="contain"
            height={(92 / 5) * 3}
            alt="google-login"
          />
        </GoogleLoginButton>
      </Content>
    </>
  );
}

const GoogleLoginButton = styled.button`
  width: calc((382px / 5) * 3);
  height: calc((92px / 5) * 3);
  padding: 0;
  border: none;
`;

const Content = styled.main`
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
`;
