import { useTheme } from '@emotion/react';
import styled from '@emotion/styled';
import Head from 'next/head';
import Link from 'next/link';

export default function BaumannIntro() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Content>
          <Link href="/baumann/question">question</Link>
          <Link href="/baumann/result">result</Link>
        </Content>
      </main>
    </>
  );
}

const Content = styled.div`
  display: flex;
  flex-direction: row;
  gap: 1rem;

  width: 100vw;
  height: 100vh;

  justify-content: center;
  align-items: center;
`;
