import Head from 'next/head';
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next';

import { ProductService } from '@/api/service';
import { Header, ProductItem } from '@/components';
import type { Product } from '@/types/product';
import { useIsUserLikeProduct, useToggleUserLike } from '@/api/query';
import React from 'react';

interface Props {
  product: Product;
}

// TODO: user 연결에 따라 아래 기능 추가
// 1. 상품 조회 api
// 2. 찜하기 기능 api
const ProductDetailPage: NextPage<Props> = ({ product }) => {
  const userId = undefined;
  const isUserLike = useIsUserLikeProduct({ userId, productId: product?.id });
  const toggleLike = useToggleUserLike({ userId, productId: product?.id });

  const handleClickToggleLike = React.useCallback(() => {
    if (userId) {
      toggleLike.mutate();
    } else {
      alert('You have to log in to add the product to the wishlist.');
    }
  }, [toggleLike, userId]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main style={{ paddingInline: 34, paddingBlock: 80 }}>
        <ProductItem
          product={product}
          like={isUserLike.data ?? false}
          onClickLike={handleClickToggleLike}
        />
      </main>
    </>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const productIds = await ProductService.getAllIds();

  return {
    paths: productIds.map((id) => ({ params: { id: String(id) } })),
    fallback: true,
  };
};

export const getStaticProps: GetStaticProps<Props, { id: string }> = async ({ params }) => {
  const product = await ProductService.getProduct(params?.id ?? '1');

  return {
    props: {
      product: product,
    },
  };
};

export default ProductDetailPage;
